kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tls.crt: |-
    {{ .Files.Get "certificate.txt" | b64enc }}
  tls.key: |-
    {{ .Files.Get "key.txt" | b64enc }}
