apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Svcname }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.Appname }}
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.Appname }}
