# Default values for miqp-ui-dep.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
##################Names of files and Applications################
Depname: miqp-ui-dep
Appname: miqp-ui
Svcname: miqp-ui-svc
Ingname: miqp-ing
##################################################################
replicaCount: 2
strategy: 
  type: RollingUpdate
  rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
minReadySeconds: 5
nodeSelector:
       role: nginxplus
image:
  repository: 230367374156.dkr.ecr.us-east-1.amazonaws.com/miqp-devops
  tag: 12Sep
  pullPolicy: IfNotPresent
service:
  name: miqp-ui-svc
  externalPort: 80
  internalPort: 80
